---
- name: system -> motify limit configure
  # /etc/security/limits.conf
  pam_limits:
    domain: '{{ item.domain }}'
    limit_type: '{{ item.limit_type }}'
    limit_item: '{{ item.limit_item }}'
    value: '{{ item.value }}'
  with_items: '{{ var_limit_policy_list }}'
