---
- import_tasks: init.sys.info.yml

- import_tasks: init.sys.env.yml

- import_tasks: init.sys.time.yml

- import_tasks: init.sys.limit.yml

- import_tasks: init.sys.ctl.yml

- import_tasks: init.sys.swap.yml

- import_tasks: init.firewall.yml

- name: system -> selinux -> disable
  ansible.posix.selinux:
    policy: targeted
    state: disabled


- block:
  - name: system -> hostname -> init
    shell: 'hostnamectl set-hostname {{ hostname }}'

  - name: system -> hostname -> apply -> reboot
    reboot:
      reboot_timeout: '{{ ansible_default_reboot_timeout }}'

  when:
    - hostname is defined
    - hostname != ansible_hostname


- name: create runtime folder
  file:
    path: '{{ var_runtime_folder }}'
    state: directory
    mode: '0777'
  notify:
    - system -> clean
  changed_when: True
