---
# build setting

var_env_package_list:
  # base
  - { name: pcre-devel }
  - { name: openssl-devel }
  - { name: systemd-devel }

var_src_list:
  - { name: 'haproxy', src: '{{ var_haproxy_name }}', url: '{{ var_haproxy_url_download }}', dest: '{{ var_runtime_folder }}/{{ var_haproxy_name }}', final_dest: '{{ var_runtime_folder }}', checksum: '{{ var_haproxy_check_sum_256 }}' }

# haproxy version setting
var_haproxy_version: 2.4.2
var_haproxy_url: http://www.haproxy.org/download/2.4/src/
var_haproxy_check_sum_256_list: {
  2.4.0: 0a6962adaf5a1291db87e3eb4ddf906a72fed535dbd2255b164b7d8394a53640,
  2.4.1: 1b2458b05e923d70cdc00a2c8e5579c2fcde9df16bbed8955f3f3030df14e62e,
  2.4.2: edf9788f7f3411498e3d7b21777036b4dc14183e95c8e2ce7577baa0ea4ea2aa,
}
