---
# docker version setting
var_docker_ce_version: '{{ var_docker_ce_version_basic }}.el{{ var_os_centos_version }}'
var_docker_ce_cli_version: '{{ var_docker_ce_cli_version_basic }}.el{{ var_os_centos_version }}'
var_docker_containerd_version: '{{ var_docker_containerd_version_basic }}.el{{ var_os_centos_version }}'
var_docker_ce_rootless_extras_version: '{{ var_docker_ce_rootless_extras_version_basic }}.el{{ var_os_centos_version }}'
var_docker_plugin_scan_version: '{{ var_docker_plugin_scan_version_basic }}.el{{ var_os_centos_version }}'

var_docker_ce_name: 'docker-ce-{{ var_docker_ce_version }}.x86_64.rpm'
var_docker_ce_cli_name: 'docker-ce-cli-{{ var_docker_ce_cli_version }}.x86_64.rpm'
var_docker_ce_rootless_extras_name: 'docker-ce-rootless-extras-{{ var_docker_ce_rootless_extras_version }}.x86_64.rpm'
var_docker_containerd_name: 'containerd.io-{{ var_docker_containerd_version }}.x86_64.rpm'
var_docker_docker_compose_name: 'docker-compose-Linux-x86_64'
var_docker_plugin_scan_name: 'docker-scan-plugin-{{ var_docker_plugin_scan_version }}.x86_64.rpm'

var_docker_ce_check_sum_256: '{{ var_docker_ce_check_sum_256_list[ var_docker_ce_version ] }}'
var_docker_ce_cli_check_sum_256: '{{ var_docker_ce_cli_check_sum_256_list[ var_docker_ce_cli_version ] }}'
var_docker_ce_rootless_extras_check_sum_256: '{{ var_docker_ce_rootless_extras_check_sum_256_list[ var_docker_ce_rootless_extras_version ] }}'
var_docker_containerd_check_sum_256: '{{ var_docker_containerd_check_sum_256_list[ var_docker_containerd_version ] }}'
var_docker_compose_check_sum_256: '{{ var_docker_compose_check_sum_256_list[ var_docker_compose_version ] }}'
var_docker_plugin_scan_check_sum_256: '{{ var_docker_plugin_scan_check_sum_256_list[ var_docker_plugin_scan_version ] }}'

# docker download setting
var_docker_compose_url_download: '{{ var_docker_compose_url }}/{{ var_docker_compose_version }}'


# docker extend module
var_docker_ctop_name: 'ctop-{{ var_docker_ctop_version }}-linux-amd64'

var_docker_ctop_check_sum_256: '{{ var_docker_ctop_check_sum_256_list[ var_docker_ctop_version ] }}'

var_docker_ctop_url_download: '{{ var_docker_ctop_url }}/v{{ var_docker_ctop_version }}'
