---

ansible_default_reboot_timeout: 300

var_timezone: 'Asia/Hong_Kong'

var_env_package_list:
  # base
  - { name: epel-release }
  - { name: yum-utils }
  - { name: dkms }
  - { name: firewalld }
  - { name: bash-completion }
  - { name: sshpass }
  # - { name: environment-modules }

  # system common libs
  # - { name: 'kernel-headers-{{ ansible_facts.kernel }}' }
  # - { name: 'kernel-devel-{{ ansible_facts.kernel }}' }

  # builder
  - { name: make }
  - { name: cmake }

  # compiler
  - { name: gcc }
  - { name: gcc-c++ }

  - { name: patch }
  - { name: perl }
  - { name: pkg-config }

  - { name: '@Development tools'}

  # OS monitor
  - { name: htop }
  - { name: lsof }
  - { name: dstat }
  - { name: iotop }
  - { name: iftop }
  - { name: nload }
  - { name: screen }
  - { name: tmux }
  - { name: sysstat }
  - { name: tcpdump }
  - { name: net-tools }
  - { name: bind-utils }

  # software -> basic
  - { name: lvm2 }
  - { name: vim }
  - { name: curl }
  - { name: wget }
  - { name: unzip }
  - { name: rsync }
  - { name: lrzsz }

var_firewall_policy_list:
  - { name: 'http',  service: 'web', zone: 'public', type: tcp, port: 80, state: enabled, permanent: yes }
  - { name: 'https', service: 'web', zone: 'public', type: tcp, port: 443, state: enabled, permanent: yes }
  - { name: 'dhcpv6-client', state: 'disabled' , type: 'service', permanent: yes }

var_limit_policy_list:
  - { domain: 'root', limit_type: 'soft', limit_item: 'nofile', value: 65536 }
  - { domain: 'root', limit_type: 'hard', limit_item: 'nofile', value: 65536 }
  - { domain: '*', limit_type: 'soft', limit_item: 'nofile', value: 65536 }
  - { domain: '*', limit_type: 'hard', limit_item: 'nofile', value: 65536 }

var_sysctl_policy_list:
  - { name: 'vm.swappiness', value: 0 }
  - { name: 'net.ipv4.ip_forward', value: 1 }

  # Disable IPV6
  - { name: 'net.ipv6.conf.all.disable_ipv6', value: 1 }
  - { name: 'net.ipv6.conf.default.disable_ipv6', value: 1 }

  # TCP
  - { name: 'net.ipv4.tcp_syncookies', value: 1 }
  - { name: 'net.ipv4.tcp_tw_reuse', value: 1 }
  - { name: 'net.ipv4.tcp_tw_recycle', value: 1 }
  - { name: 'net.ipv4.tcp_max_tw_buckets', value: "{{ 5 * 1024 }}" }
  - { name: 'net.ipv4.tcp_max_syn_backlog', value: "{{ 8 * 1024 }}" }
  - { name: 'net.ipv4.tcp_fin_timeout', value: 30 }
  - { name: 'net.ipv4.tcp_synack_retries', value: 2 }

  # IO
  - { name: 'fs.inotify.max_user_watches', value: "{{ 2048 * 1024 }}" }
  - { name: 'fs.inotify.max_user_instances', value: "{{ 2048 * 1024 }}" }

  # MYSQL - innodb_use_native_aio
  - { name: 'fs.aio-max-nr', value: "{{ 1024 * 1024 }}" }
